// To add, edit, or remove a channel, just update the list below.
// The app will automatically fetch the latest videos from these channels.
// The first channel in the list is prioritized in the feed.
export const channelUrls = [
  'https://www.youtube.com/@KannadaTechForYou',
  'https://www.youtube.com/@techinkannada360',
  'https://www.youtube.com/c/TechnicalGuruji',
  'https://www.youtube.com/@TechBurner',
  'https://www.youtube.com/c/TrakinTechEnglish',
  'https://www.youtube.com/c/TechBar',
  'https://www.youtube.com/beebomco', // Prasad Tech in Telugu
  'https://www.youtube.com/channel/UC1tVU8H153ZFO9eRsxdJlhA', // Technology Gyan
  'https://www.youtube.com/c/DrBro',
  'https://www.youtube.com/c/DrJagdishChatur',
  'https://www.youtube.com/c/VismayaKannadaVK',
  'https://www.youtube.com/c/KannadaDolu',
  'https://www.youtube.com/c/RakazoneGaming',
  'https://www.youtube.com/c/JagdishChaturvedi',
  'https://youtube.com/@thepowerhousevines',
  'https://youtube.com/@vaisshnavistudios',
  'https://youtube.com/@royalchallengersbengaluruyt',
  'https://youtube.com/@haylsworld',
  'https://youtube.com/@techysomzkannada',
  'https://youtube.com/@ganeshkaranthcrictalks',
  'https://youtube.com/@bhatnbhat',
  'https://youtube.com/@skandyyman',
  'https://youtube.com/@mundhebanni',
  'https://youtube.com/@angular',
  'https://youtube.com/@firebase',
  'https://www.youtube.com/@Apple',
  'https://www.youtube.com/@Groww',
  'https://youtube.com/@ganeshkaranth',
  'https://youtube.com/@rajshamani',
  'https://youtube.com/@trakintech',
  'https://youtube.com/@primevideoin',
  'https://youtube.com/@techwiser',
  'https://youtube.com/@nickbradley',
  'https://youtube.com/@fireship',
  'https://youtube.com/@theallrounderrs',
  'https://youtube.com/@netflixindiaofficial',
  'https://youtube.com/@aiyyoshraddha',
  'https://youtube.com/@flyingpassport',
  'https://www.youtube.com/@in28minutes',
  'https://www.youtube.com/@Telusko',
  'https://www.youtube.com/@LearningPartnerDigital',
  'https://www.youtube.com/@theigorsedov',
  'https://www.youtube.com/@Sanjay_Kathuria',
  'https://www.youtube.com/@EngineeringDigest',
];
