// To add, edit, or remove a channel, just update the list below.
// The app will automatically fetch the latest videos from these channels.
// The first channel in the list is prioritized in the feed.
export const channelUrls = [
  'https://www.youtube.com/@techinkannada360',
  'https://www.youtube.com/@Apple',
  'https://www.youtube.com/@Groww',
  'https://youtube.com/@ganeshkaranth',
  'https://youtube.com/@rajshamani',
  'https://youtube.com/@trakintech',
  'https://www.youtube.com/c/TechnicalGuruji',
  'https://www.youtube.com/@TechBurner',
  'https://www.youtube.com/c/TrakinTechEnglish',
  'https://www.youtube.com/c/TechBar',
  'https://www.youtube.com/beebomco',
  'https://www.youtube.com/channel/UCmJlSkSkgdXama3GSUgMC4g', // Trakin Tech Tamil Official
  'https://www.youtube.com/channel/UCb-xXZ7ltTvrh9C6DgB9H-Q', // Prasad Tech in Telugu
  'https://www.youtube.com/channel/UC1tVU8H153ZFO9eRsxdJlhA', // Technology Gyan
  'https://www.youtube.com/c/DrBro',
  'https://www.youtube.com/c/RekhaAduge',
  'https://www.youtube.com/c/RajaniAduge',
  'https://www.youtube.com/c/TanuSwayamAduge',
  'https://www.youtube.com/c/SimplellagiOnduAduge',
  'https://www.youtube.com/c/ShrideviVlogs',
  'https://www.youtube.com/c/DanishSait',
  'https://www.youtube.com/c/ShrutiPrakash',
  'https://www.youtube.com/c/TasteWithIbrahim',
  'https://www.youtube.com/c/SujathaKS',
  'https://www.youtube.com/c/KannadaTechForYou',
  'https://www.youtube.com/c/GaneshKaranth',
  'https://www.youtube.com/c/DrJagdishChatur',
  'https://www.youtube.com/c/VismayaKannadaVK',
  'https://www.youtube.com/c/KannadaDolu',
  'https://www.youtube.com/c/RakazoneGaming',
  'https://www.youtube.com/c/JagdishChaturvedi',
  'https://www.youtube.com/c/TanuAdugeSpecial',
  'https://youtube.com/@thepowerhousevines',
  'https://youtube.com/@vaisshnavistudios',
  'https://youtube.com/@royalchallengersbengaluruyt',
  'https://youtube.com/@haylsworld',
  'https://youtube.com/@techysomzkannada',
  'https://youtube.com/@ganeshkaranthcrictalks',
  'https://youtube.com/@bhatnbhat',
  'https://youtube.com/@primevideoin',
  'https://youtube.com/@skandyyman',
  'https://youtube.com/@mundhebanni',
  'https://youtube.com/@angular',
  'https://youtube.com/@firebase',
];
